<!doctype html><html lang=en><head><title>django :: Lambda</title><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=description content><meta name=keywords content><meta name=robots content="noodp"><link rel=canonical href=/tags/django/><link rel=stylesheet href=/style.css><link rel="shortcut icon" href=/img/theme-colors/orange.png><link rel=apple-touch-icon href=/img/theme-colors/orange.png><meta name=twitter:card content="summary"><meta property="og:locale" content="en"><meta property="og:type" content="website"><meta property="og:title" content="django"><meta property="og:description" content><meta property="og:url" content="/tags/django/"><meta property="og:site_name" content="Lambda"><meta property="og:image" content="img/favicon/%!s().png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="627"><link href=/tags/django/index.xml rel=alternate type=application/rss+xml title=Lambda></head><body><div class="container headings--one-size"><header class=header><div class=header__inner><div class=header__logo><a href=/><div class=logo>Terminal</div></a></div><ul class="menu menu--mobile"><li class=menu__trigger>Menu&nbsp;▾</li><li><ul class=menu__dropdown><li><a href=/>Home</a></li><li><a href=/blog/>Blog</a></li><li><a href=/categories/>Categories</a></li></ul></li></ul></div><nav class=navigation-menu><ul class="navigation-menu__inner menu--desktop"><li><a href=/>Home</a></li><li><a href=/blog/>Blog</a></li><li><a href=/categories/>Categories</a></li></ul></nav></header><div class=content><div class=posts><article class="post on-list"><h1 class=post-title><a href=/blog/how-to-fix-no-route-found-error-on-django-channels/>How to fix no route found error on Django Channels</a></h1><div class=post-meta><time class=post-date>2020-01-25 ::</time>
<span class=post-author>lambda@lambda.tw</span></div><span class=post-tags>#<a href=/tags/django/>Django</a>&nbsp;
#<a href=/tags/django-channels/>Django Channels</a>&nbsp;
#<a href=/tags/middleware/>Middleware</a>&nbsp;</span><div class=post-content>Issue description Django Channels 對於不存在的路徑存取，全部會拋出錯誤，而不是一般性的警告處理，所以如果和我一樣在 Djangoo Channels 有裝上 Sentry ，而且伺服器在被惡意嘗試路徑時就會看到一堆 ValueError: No route found for path &lsquo;&mldr;&rsquo;. 的錯誤資訊，好處是知道被打了，壞處就是會噴錢（如果不是自己 Hosting）。
Fix it Make HandleRouteNotFoundMiddleware for this issue from datetime import datetime from logging import getLogger from django.urls.exceptions import Resolver404 logger = getLogger(<strong>file</strong>) class HandleRouteNotFoundMiddleware: def <strong>init</strong>(self, inner): self.inner = inner def <strong>call</strong>(self, scope): try: inner_instance = self.inner(scope) return inner_instance except (Resolver404, ValueError) as e: if 'No route found for path' not in str(e) and \ scope["type"] not in ['http', 'websocket']: raise e logger.</div><div><a class="read-more button" href=/blog/how-to-fix-no-route-found-error-on-django-channels/>→</a></div></article><article class="post on-list"><h1 class=post-title><a href=/blog/create-a-gin-index-with-django-on-aws-rds/>Create a GIN index with Django on AWS RDS</a></h1><div class=post-meta><time class=post-date>2019-04-26 ::</time>
<span class=post-author>lambda@lambda.tw</span></div><span class=post-tags>#<a href=/tags/index/>Index</a>&nbsp;
#<a href=/tags/postgres/>postgres</a>&nbsp;
#<a href=/tags/django/>Django</a>&nbsp;
#<a href=/tags/aws/>AWS</a>&nbsp;
#<a href=/tags/rds/>RDS</a>&nbsp;</span><div class=post-content>GIN What is it GIN 是一種 INDEX 可以幫助加速全文搜索的速度
GIN stands for Generalized Inverted Index. GIN is designed for handling cases where the items to be indexed are composite values, and the queries to be handled by the index need to search for element values that appear within the composite items. For example, the items could be documents, and the queries could be searches for documents containing specific words.
Normal SQL 在傳統 SQL 下可以用以下幾個步驟完成建立 GIN INDEX</div><div><a class="read-more button" href=/blog/create-a-gin-index-with-django-on-aws-rds/>→</a></div></article><article class="post on-list"><h1 class=post-title><a href=/blog/closure/>Closure</a></h1><div class=post-meta><time class=post-date>2019-04-18 ::</time>
<span class=post-author>lambda@lambda.tw</span></div><span class=post-tags>#<a href=/tags/python/>python</a>&nbsp;
#<a href=/tags/closure/>closure</a>&nbsp;
#<a href=/tags/django/>django</a>&nbsp;
#<a href=/tags/django-q/>django q</a>&nbsp;
#<a href=/tags/lisp/>lisp</a>&nbsp;</span><div class=post-content>Closure What is closure Closure 簡單來說，就是某函數在另一個函數內被創造並且參照了創建函數的某些變數，此時該變數會存留於記憶內，儘管創建函數已經結束。
First time meet to Closure N年前在學習 Common Lisp 時教學內出現了一個陌生又奇特的技巧，Closure，以下是他的實做
(let ((counter 0)) (defun reset () (setf counter 0)) (defun stamp () (setf counter (+ counter 1)))) (list (stamp) (stamp) (reset) (stamp)) ; (1 2 0 1) 為了怕正常人看不懂，以下用 Python 翻譯
def gen_counter(): counter = 0 def reset(): nonlocal counter counter = 0 return counter def stamp(): nonlocal counter counter += 1 return counter return reset, stamp reset, stamp = gen_counter() print(stamp()) # 1 print(stamp()) # 2 print(reset()) # 0 print(stamp()) # 1 可以看出在 gen_counter 內的 兩個函數 (reset, stamp) 一同共用內部變數 counter 儘管 gen_counter 已經回傳並且結束，但是在之後的程式卻還是擁有當初初始化的 count，亦即 counter 在記憶體中不會因為 gen_counter 已經回傳就被回收。</div><div><a class="read-more button" href=/blog/closure/>→</a></div></article><div class=pagination><div class=pagination__buttons></div></div></div></div><footer class=footer><div class=footer__inner><div class=copyright><span>© 2022 Powered by <a href=http://gohugo.io>Hugo</a></span>
<span>:: Theme made by <a href=https://twitter.com/panr>panr</a></span></div></div></footer><script type=text/javascript src=/bundle.min.js></script></div></body></html>